# A script to organize the MACA data for Mt Sunapee
#!/bin/bash
#PBS -A ren10_d_g_sc_eesi
#PBS -l nodes=1:ppn=1
#PBS -l walltime=2:00:00

cd /gpfs/group/eesi/default/users/klr324/precipVis/precipVisualization/code

singularity exec -B /gpfs/group/eesi/default/users/klr324/communityClimateOutlooks/:/base /gpfs/group/kzk10/default/private/ren10/mlisk_collab/cntyTimeSeries_code/climateOutlookEnvCDOncl.simg Rscript organizeMACA.R "mtsunapeeNH_50km/" "mtsunapeeNH_50km"

singularity exec -B /gpfs/group/eesi/default/users/klr324/communityClimateOutlooks/:/base /gpfs/group/kzk10/default/private/ren10/mlisk_collab/cntyTimeSeries_code/climateOutlookEnvCDOncl.simg Rscript organizeMACA.R "mtsunapeeNH_100km/" "mtsunapeeNH_100km"

singularity exec -B /gpfs/group/eesi/default/users/klr324/communityClimateOutlooks/:/base /gpfs/group/kzk10/default/private/ren10/mlisk_collab/cntyTimeSeries_code/climateOutlookEnvCDOncl.simg Rscript organizeMACA.R "mtsunapeeNH_150km/" "mtsunapeeNH_150km"

singularity exec -B /gpfs/group/eesi/default/users/klr324/communityClimateOutlooks/:/base /gpfs/group/kzk10/default/private/ren10/mlisk_collab/cntyTimeSeries_code/climateOutlookEnvCDOncl.simg Rscript organizeMACA.R "mtsunapeeNH_200km/" "mtsunapeeNH_200km"
