# A script to summarizing the GridMet data for Wasco, CA for 50km to 200km
#!/bin/bash
#PBS -A ren10_d_g_sc_eesi
#PBS -l nodes=1:ppn=1
#PBS -l walltime=10:00:00

cd /gpfs/group/eesi/default/users/klr324/precipVis/precipVisualization/code

#50km
#singularity exec -B /gpfs/group/eesi/default/users/klr324/precipVis/precipVisualization/:/base /gpfs/group/kzk10/default/private/ren10/mlisk_collab/cntyTimeSeries_code/climateOutlookEnvCDOncl.simg Rscript summNCoutput_gridMet.R "wascoCA_50km/" "wascoCA_50km"
#100km
singularity exec -B /gpfs/group/eesi/default/users/klr324/precipVis/precipVisualization/:/base /gpfs/group/kzk10/default/private/ren10/mlisk_collab/cntyTimeSeries_code/climateOutlookEnvCDOncl.simg Rscript summNCoutput_gridMet.R "wascoCA_100km/" "wascoCA_100km"
#150km
#singularity exec -B /gpfs/group/eesi/default/users/klr324/precipVis/precipVisualization/:/base /gpfs/group/kzk10/default/private/ren10/mlisk_collab/cntyTimeSeries_code/climateOutlookEnvCDOncl.simg Rscript summNCoutput_gridMet.R "wascoCA_150km/" "wascoCA_150km"
#200km
#singularity exec -B /gpfs/group/eesi/default/users/klr324/precipVis/precipVisualization/:/base /gpfs/group/kzk10/default/private/ren10/mlisk_collab/cntyTimeSeries_code/climateOutlookEnvCDOncl.simg Rscript summNCoutput_gridMet.R "wascoCA_200km/" "wascoCA_200km"

